### ISSUE TITLE
how to add a new color dont exist like ORANGE?

### ISSUE THREAD

**Issue by Yansoltion** [ognjen-petrovic/js-dxf#101]

**Comment by tarikjabiri** [comment]
Hi

You can visit this website [AutoCAD Color Index](https://gohtx.com/acadcolors.php), and choose a color and pick its number. So the orange its number is 30.

```js
d.addLayer('l_orange', 30, 'CONTINUOUS'); // This layer will be orange
```
Regards

**Comment by Yansoltion** [comment]
Thank you..
What about font family?

Le mer. 10 mai 2023, 14:05, EL JABIRI Tarik ***@***.***> a
écrit :
