### ISSUE TITLE
Units are always inches. need support for mm.

### ISSUE THREAD

**Issue by kannanlink3d** [ognjen-petrovic/js-dxf#15]
there should be option to save file in desired units. 
Currently it always saves in inches.

**Comment by ognjen-petrovic** [comment]
Yes, that would be nice feature. Will investigate.
If you have an idea how to do that, please do and make PR.

**Comment by ognjen-petrovic** [comment]
I have added unit support. Checkout "units" branch.
Check circle and line examples.
Available units find in Drawing.js,  search for Drawing.UNITS.
I checked in LibreCad and DraftSight.

**Comment by kannanlink3d** [comment]
Thanks for adding the units.
