### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by jhenson29** [ognjen-petrovic/js-dxf#19]
Is there any interest in converting this project to TypeScript? 

I can help if there is interest.

**Comment by ognjen-petrovic** [comment]
Hi Jeremy,
Thanks for your interest in this.
I have not had such plan so far.
This is fairly simple project and I'm not sure what would be benefit of TS?
Regards, Ognjen

**Comment by jhenson29** [comment]
The benefit is when used in other TypeScript projects. It's always nice when the typings are bundled into the source project. It would still compile to JS and still be published on npm in JS, but it would include the d.ts files for TypeScript. 

No problem if you aren't interested. I just thought I'd ask/offer. I may add types to @types for this project later. I just have wrappers in my code for everything right now.

Great project. Thanks for making this.
