### ISSUE TITLE
Add support for text alignment

### ISSUE THREAD

**Issue by jhenson29** [ognjen-petrovic/js-dxf#20]
I think it's a relatively simple change to add support for horizontal and vertical text alignment.

It only involves adding those two parameters and adding the 11, 21, 31, 72, and 73 group codes to the dxf string builder (and updating docs).

I think the the parameters can be added with default values to preserve backwards compatibility.

Any plans to implement text alignment?
Or would you accept a PR?

**Comment by ognjen-petrovic** [comment]
Hi Jeremy,

That would be great..yes please do a PR.

Thanks, Ognjen

**Comment by jhenson29** [comment]
Okay. I think there are two ways to add this in:

### 1. Always add in the extra group codes
  **pro** - this is the cleanest code because there are no conditionals
  **con** - while this shouldn't break actual DXF rendering because the group codes specification states that certain codes are ignored if other codes are `0`, it may break user tests that look at snapshots. Technically, the output would be different in this version.

option 1 looks something like this:
```javascript
// declare codes
const H_ALIGN_CODES = ['left', 'center', 'right'];
const V_ALIGN_CODES = ['baseline','bottom', 'middle', 'top'];

// lookup codes
s += `11\n${this.x1}\n21\n${this.y1}\n31\n0\n`;
s += `72\n${Math.max(H_ALIGN_CODES.indexOf(this.hAlign),0)}\n`;
s += `73\n${Math.max(V_ALIGN_CODES.indexOf(this.vAlign),0)}\n`;
```

### 2. Only add in the extra group codes if an alignment parameter requires it
  **pro** - this method would have no changes to the output for existing code bases
  **con** - the implementation is messier because of the regex and conditional. It can be done without the regex, but the conditionals get significantly messier. I played with if/else, ternaries, and switch statements. The was the cleanest I could get it.

option 2 looks something like this:
```javascript
// declare codes AND create regex for testing
const H_ALIGN_CODES = ['left', 'center', 'right'];
const V_ALIGN_CODES = ['baseline','bottom', 'middle', 'top'];
const H_ALIGN_REGEX = new RegExp(`(^${H_ALIGN_CODES.slice(1).join('|')})$`);
const V_ALIGN_REGEX = new RegExp(`(^${V_ALIGN_CODES.slice(1).join('|')})$`);

// only add codes if either hAlign or vAlign calls for it
if (H_ALIGN_REGEX.test(this.hAlign) | V_ALIGN_REGEX.test(this.vAlign)){
    s += `11\n${this.x1}\n21\n${this.y1}\n31\n0\n`;
    s += `72\n${Math.max(H_ALIGN_CODES.indexOf(this.hAlign),0)}\n`;
    s += `73\n${Math.max(V_ALIGN_CODES.indexOf(this.vAlign),0)}\n`;
}
```

Please let me know your thoughts.

**Comment by ognjen-petrovic** [comment]
I vote for option two.

Would be possible to use [includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) instead of regex.

So this:
```
const H_ALIGN_CODES = ['left', 'center', 'right']
const H_ALIGN_REGEX = new RegExp(`(^${H_ALIGN_CODES.slice(1).join('|')})$`)
H_ALIGN_REGEX.test(this.hAlign)
```
becomes:
```
const H_ALIGN_CODES = ['left', 'center', 'right']
H_ALIGN_CODES.includes(this.hAlign, 1)
```

**Comment by jhenson29** [comment]
Yes, of course! Thank you for pointing that out.

**Comment by ognjen-petrovic** [comment]
New version with you updates has been published to npm.
Thanks.
