### ISSUE TITLE
Example output fails to open in AutoCAD 2021

### ISSUE THREAD

**Issue by yowzadave** [ognjen-petrovic/js-dxf#48]
Trying to open any file generated by this library in AutoCAD 2021 (for Mac) returns the following error:

```
Unknown group 74 for table on line 78.
Invalid or incomplete DXF input — drawing discarded.
```

This is true if I regenerate the file `examples/demo.js.dxf`.

**Comment by janvorisek** [comment]
I'm having the same error even if using `d.header('ACADVER', [[1, 'AC1009']])`

**Comment by janvorisek** [comment]
Still having a similar error even with `generateAutocadExtras()` in AutoCAD 2020 on Windows.

```
Incorrect group 330 in table head on line 36.
Invalid or incomplete DXF input -- drawing discarded.
```

I'm drawing just lines like this:

```
const d = new Drawing();

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
d.header('ACADVER', [[1, 'AC1009']]);

d.setUnits('Decimeters');

d.drawLine(...);

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
d.generateAutocadExtras();
fs.writeFileSync('test.dxf', d.toDxfString());
```

Seems like typings are also wrong, but that's not a big deal in the moment, I'll send PR when I have time.

**Comment by agviegas** [comment]
Hi @thisismhp! We want to use this in [ifc.js](https://ifcjs.github.io/info/) to allow users to export DXF files out of IFC files. We are successfully able to generate DXF files that can be read by several viewers (e.g. ODA dxf viewer), but unfortunately AutoCad won't load the output. 

We've tried to use `currentDrawing.generateAutocadExtras();` before `const serialized = currentDrawing.toDxfString();`, but even then AutoCAD it's unable to load it. We've tried with AutoCAD 2017 and 2020. You can find the generated file [here](https://drive.google.com/file/d/1icD3ifD87LgtXbS-kj3XW2WwRYWZB6Wl/view?usp=sharing). It's the same as the image below but without the projected lines. 

Is there  any code snippet that we can look that generates a drawing that AutoCAD can open?

Thanks in advance!

![image](https://user-images.githubusercontent.com/56475338/154048518-a3145de3-edf0-4772-8d13-b97066f7517e.png)
