### ISSUE TITLE
block support with example

### ISSUE THREAD

**Issue by tologonkudaiberdiuulu** [ognjen-petrovic/js-dxf#51]
Hi!. I looked for writer and noticed that there block and block record entities. But in the examples there is no example at all. And I also looked for "Drawing.js" file in the source. Can't find any examples of blocks how to add entities to blocks and how to write it to dxf('Cause in the block and blockrecord files, there's no entities included while writing to dxf. According [dxf block documentation](https://documentation.help/AutoCAD-DXF/WS1a9193826455f5ff18cb41610ec0a2e719-795f.htm), enities must be included in blocks.

**Comment by ognjen-petrovic** [comment]
Hi,

Unfortunately, blocks are not implemented.
