### ISSUE TITLE
Add Line3d as a new DatabaseObject

### ISSUE THREAD

**Issue by ieskudero** [ognjen-petrovic/js-dxf#52]
The current Line implementation doesn't allow to enter the z value of a point, although the dxf format allows it. For our project we need to have 3d lines (tryed with 3dpolylines but it triangulates the  output) and I have implemented them, but I am unable to load changes since github added the pat authentication (That is why I opened an issue, instead of a pull request). I can send you the files if you want.

**Comment by ognjen-petrovic** [comment]
OK. Send it.
Thanks.

**Comment by ieskudero** [comment]
Done! should arrive to your email an weTransfer email with the files
