### ISSUE TITLE
polygon support

### ISSUE THREAD

**Issue by clavijojuan** [ognjen-petrovic/js-dxf#67]
can you add polygon supporting? thanks

**Comment by ognjen-petrovic** [comment]
Hi,

That is possible. How would you like to define a polygon?

**Comment by ognjen-petrovic** [comment]
Tarik suggested: 

drawPolygon(x_center, y_center, number_of_sides, radius, circumscribed = false)

and it use polyline

**Comment by tarikjabiri** [comment]
Hi,

AutoCAD support Polygon as a polyline enity.
It ask for a center, a radius and a number of sides
It support only regular polygon
A polygon also might be inscribed or circumscribed.

**Comment by tarikjabiri** [comment]
# Example:
![polygon](https://user-images.githubusercontent.com/6343314/150641766-d9fd953d-c411-4287-bea5-c1a6b0dfcc0f.png)

**Comment by clavijojuan** [comment]
Thanks, please add to Readme 👍

**Comment by tarikjabiri** [comment]
For an example please see [polygon.js](https://github.com/ognjen-petrovic/js-dxf/blob/master/examples/polyline.js).

**Comment by clavijojuan** [comment]
i was referring to "Supported entities" in the ReadME file

**Comment by ognjen-petrovic** [comment]
Added to Readme and published

@tarikjabiri Thanks
