### ISSUE TITLE
style point support

### ISSUE THREAD

**Issue by clavijojuan** [ognjen-petrovic/js-dxf#68]
Hi,

is possible to implement style support to point entities? In AUTOCAD you can set the style of points like this: 

![image](https://user-images.githubusercontent.com/57905996/150820309-f37da0e0-a554-47f8-8332-8ed31a3fecba.png)

Thanks

**Comment by ognjen-petrovic** [comment]
According to this https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2019/ENU/AutoCAD-Core/files/GUID-82F9BB52-D026-4D6A-ABA6-BF29641F459B-htm.html it is possible
Setting PDMODE and PDSIZE should change point style. I have not tried, will do that latter...

**Comment by clavijojuan** [comment]
Okay thanks, I will be pending 👍

**Comment by clavijojuan** [comment]
> Hi @tarikjabiri,
> 
> I tried your example (following image) :
> 
> ![image](https://user-images.githubusercontent.com/57905996/151019222-6672c0ad-3391-45ed-92bf-d47d126fc095.png)
> 
> but in the document i got this errors:
> 
> ![image](https://user-images.githubusercontent.com/57905996/151019346-89be1396-562f-4775-abdc-d3500dbeb13b.png)
> 
> can you help me please?

I modified the values manually and finally can open the file on AUTOCAD, but the file have to be in the following structure

![image](https://user-images.githubusercontent.com/57905996/151022050-099cdad7-ef51-441a-b4e9-d08507e1b79a.png)

do you know where is the error?

**Comment by tarikjabiri** [comment]
Hi,

I am sorry my bad the code should look like this:

```js 
d.header("PDMODE", [[70, 32]]);
d.header("PDSIZE", [[40, 10]]); 
```

Array of arrays

**Comment by clavijojuan** [comment]
Hi, 
PDMODE fixed but can't open in AUTOCAD
![image](https://user-images.githubusercontent.com/57905996/151024238-c2a02eed-9ebb-4ee2-9426-a194cb4cb2ee.png)

**Comment by tarikjabiri** [comment]
Hi,

Is this dxf content generated by `js-dxf` ?

![151024238-c2a02eed-9ebb-4ee2-9426-a194cb4cb2ee](https://user-images.githubusercontent.com/6343314/151026864-9ce49009-b178-43ed-8bb7-02da2e71895d.png)

The 9 should be 0.

Did you change it manually ?

The dxf generated work fine.

I tried this example is working fine:

```js
const d = new Drawing();

d.header("PDMODE", [[70, 32]]);
d.header("PDSIZE", [[40, 5]]);

d.drawPoint(0,0);
d.drawPoint(10,10);
```

Result:

![point](https://user-images.githubusercontent.com/6343314/151028310-5a1dddc4-d0b1-40df-9f0b-4ac4b42150ae.PNG)

The issue is resolved please close this issue

Regards.

**Comment by clavijojuan** [comment]
Okay with your code it works, but i have a question : 

![image](https://user-images.githubusercontent.com/57905996/151029792-866a6f57-59f5-4c1c-af66-177803f8a6fe.png)

i want the number 3 not 32, so should be the following the code ?

![image](https://user-images.githubusercontent.com/57905996/151029938-912ba5c8-b20b-4ef7-8dd6-6a53d42d5925.png)

Thank you for everything!

**Comment by ognjen-petrovic** [comment]
@tarikjabiri @tarikjabiri Great, thanks.
Wondering would it be helpful to  add method "setPointStyle" to Drawing class?
