### ISSUE TITLE
set UCS origin

### ISSUE THREAD

**Issue by clavijojuan** [ognjen-petrovic/js-dxf#69]
Hi.

i want to ask if is possible add "set UCS origin" method ?

Thanks

**Comment by ognjen-petrovic** [comment]
At the moment I do not know how to do that...must investigate...

**Comment by clavijojuan** [comment]
> Hi, i don't know how to help you but i searched information about in this [link](https://damassets.autodesk.net/content/dam/autodesk/www/developer-network/platform-technologies/autocad-dxf-archive/acad_r12_dxf.pdf)
> 
> Could be help

To answer my own question, this code worked for me:

`
d.header("UCSORG", [[10,1000000], [20, 1000000], [30, 0]]);
`

where coordinates origin is (1000000, 1000000, 0)

Thanks

**Comment by ognjen-petrovic** [comment]
Would be worth adding method for this as well?

**Comment by clavijojuan** [comment]
Maybe but i think that is most important a method or function to make "zoom to layers extent"
