### ISSUE TITLE
Problems with large dataset

### ISSUE THREAD

**Issue by clavijojuan** [ognjen-petrovic/js-dxf#78]
Hi,

I'm trying to create a dxf project using this plugin but i had some troubles when create 30k of points.

I'm using forEach array method to create 30k of points but isn't efficient. There some possibility to add multiple creation instead one by one ?

Thanks.

**Comment by ognjen-petrovic** [comment]
No, there is no such possibility,
Maybe for loop would be more efficient.

**Comment by clavijojuan** [comment]
> No, there is no such possibility, Maybe for loop would be more efficient.

Didn't works. I realized that the problem is not drawing objects otherwise the d.toDxfString() method.
