### ISSUE TITLE
Easy solution for large datasets 

### ISSUE THREAD

**Issue by agviegas** [ognjen-petrovic/js-dxf#79]
Hi there!

We are using this fantastic library to generate floor plans out of BIM models with [IFC.js](https://ifcjs.github.io/info/) (I'm one of the creators). We've noticed that large datasets produces a [Maximum Call Stack Size Exceeded Error](https://anchortagdev.com/range-error-maximum-call-stack-size-exceeded-error-using-spread-operator-in-node-js-javascript/). The error is because of this line:

```js
    /**
     * Append an array of tags to the array of tags
     * @param {Tag[]} tags
     */
    addTags(tags) {
        this._tags.push(...tags);
    }
```

We have tried changing it to this:

```js
    /**
     * Append an array of tags to the array of tags
     * @param {Tag[]} tags
     */
    addTags(tags) {
        for(let tag of tags) {
            this._tags.push(tag);
        }
    }
```

Ta-dah! I've not opened a PR because I wasn't sure whether you'd like this solution. 🙂 Cheers and thanks again!

![image](https://user-images.githubusercontent.com/56475338/171213028-1539f735-98ed-4b94-8a6c-a30f9d4d5639.png)
![image](https://user-images.githubusercontent.com/56475338/171213109-b235c365-e48f-44f1-928f-92ee77c1cab7.png)

**Comment by ognjen-petrovic** [comment]
Hi,

Great. If you want, please create a PR.
Thank you.
