### ISSUE TITLE
Question regarding import/read dxf

### ISSUE THREAD

**Issue by he-yang** [ognjen-petrovic/js-dxf#80]
hi, i do notice js-dxf can program dxf wording and export as dxf.

I am wondering if it is possible , if I import and existing dxf, js-dxf then read existing dxf file, and then add new TEXT to the existing dxf and export as a new dxf file.

I am working on an application which can add text messages to autodesk dxf drawings.

**Comment by ognjen-petrovic** [comment]
There is no reading.
