### ISSUE TITLE
Cant open in Autodesk DWG TrueView 2022

### ISSUE THREAD

**Issue by hidjou** [ognjen-petrovic/js-dxf#81]
Hi,

I created a DXF output using js-dxf but when I open it in Autodesk DWG TrueView 2022 I get this error:

_DXF read error
Error in APPID Table
DXF read error on line 214.
Invalid or incomplete DXF input -- drawing discarded._

Line 214 of the DXF file has `undefined` as a value which cant be right (same thing on line 354 and 374)

I tried running `d.generateAutocadExtras()` before running `toString()` but it didnt make a difference

Here's the code I wrote to generate my output (just a simple grid)

```js
const Drawing = require('dxf-writer');
const fs = require('fs');

const BOX = [
  [-4500, 5500],
  [4500, 5500],
  [4500, -1000],
  [-4500, -1000],
];

let x = [];
let y = [];

x = BOX.map((b) => b[0]);
y = BOX.map((b) => b[1]);

const maxX = Math.max(...x);
const minX = Math.min(...x);
const maxY = Math.max(...y);
const minY = Math.min(...y);
const step = 500;

const d = new Drawing();
d.setUnits('Millimeters');

d.addLayer('grid', Drawing.ACI.BLACK, 'DASHED').setActiveLayer('grid');
for (let a = minX; a <= maxX; a += step) {
  d.drawText(a - 10, minY - 150, 100, 0, a.toString());
  d.drawLine(a, minY, a, maxY);
}

for (let a = minY; a <= maxY; a += step) {
  d.drawText(minX - 400, a, 100, 0, a.toString());
  d.drawLine(minX, a, maxX, a);
}

d.addLayer('box', Drawing.ACI.BLACK, 'DOTTED').setActiveLayer('box').drawPolyline(BOX, true, 1, 1);

fs.writeFileSync(__filename + '.dxf', d.toDxfString());
```

Any help or pointers would be highly appreciated, I checked other issues to avoid creating a duplicate but didnt find anything similar

**Comment by tarikjabiri** [comment]
Hi 

The error is in this lines:
```js
d.addLayer('grid', Drawing.ACI.BLACK, 'DASHED').setActiveLayer('grid');
// and
d.addLayer('box', Drawing.ACI.BLACK, 'DOTTED')

// Try this:
d.addLayer('grid', Drawing.ACI.LAYER, 'DASHED').setActiveLayer('grid');
d.addLayer('box', Drawing.ACI.LAYER, 'DOTTED');
```

Or pass directly the number color see [AutoCAD Color Index (ACI)](https://gohtx.com/acadcolors.php), get the color index and pass it directly :.
```js
d.addLayer('grid', 0, 'DASHED').setActiveLayer('grid');
d.addLayer('box', 0, 'DOTTED');
```
🎉 regards

**Comment by hidjou** [comment]
Ohhh, so it couldnt find the color when I passed it through `Drawing.ACI.BLACK`? interesting..

Anyway, that worked and generated it with no undefined and I was able to run it in TrueView, thank you mate, you saved me a lot of time digging! 😆
