### ISSUE TITLE
Ellips causes error when invoking toDxfString()

### ISSUE THREAD

**Issue by mmiscool** [ognjen-petrovic/js-dxf#85]
Hello,
I tried running this in the debugger on the example located here.
https://ognjen-petrovic.github.io/js-dxf/examples/browser/index.html

```
d.drawEllipse(10, 10, 5, 0, 0.5);
d.toDxfString();
```

Getting the following error when I try to export. Tried using the code from the Ellipse example also. https://github.com/ognjen-petrovic/js-dxf/blob/master/examples/ellipse.js

Not quite sure about whats wrong.
Error text is
```
dxf_bundle.js:219 Uncaught TypeError: Cannot read properties of undefined (reading 'push')
    at Ellipse.tags (dxf_bundle.js:219:17)
    at Ellipse.tags (dxf_bundle.js:329:15)
    at Layer.shapesTags (dxf_bundle.js:449:19)
    at Drawing._tagsManager (dxf_bundle.js:1537:15)
    at Drawing.toDxfString (dxf_bundle.js:1554:21)
    at <anonymous>:12:3
```

![image](https://user-images.githubusercontent.com/6439772/183546447-386f1092-6529-42c1-8128-b93b9817455f.png)

**Comment by tarikjabiri** [comment]
Hi,

```js
//Ellipse.js
//Error in this line 
super.tags();
// should pass manager
super.tags(manager); // like this
```

**Comment by ognjen-petrovic** [comment]
Published
