### ISSUE TITLE
Question related to importing in to webpack projects

### ISSUE THREAD

**Issue by mmiscool** [ognjen-petrovic/js-dxf#86]
Hello,

I was hoping that there might be some guidance or example of using this library in the context of a webpack project.

Looking for a way to import it like this.
```
import {Drawing} from "dxf-writer";
```

**Comment by tarikjabiri** [comment]
Hi,

Why not using it like:
```js
import Drawing from "dxf-writer";
```
It's working fine in `webpack@5.74.0`. At least for me.

I have a package [@tarikjabiri/dxf](https://www.npmjs.com/package/@tarikjabiri/dxf). It supports `ES Modules` and `CommonJS` out of the box written in `Typescript`. See [docs](https://dxf.vercel.app).
```js
import { DxfWriter, point3d } from "@tarikjabiri/dxf";

const dxf = new DxfWriter();
dxf.addLine(point3d(0, 0, 0), point3d(100, 100, 0));
// To get the dxf string just call the stringify() method
const dxfString = dxf.stringify();
```

Regards.
