### ISSUE TITLE
find end of shape

### ISSUE THREAD

**Issue by ashleycoker** [ognjen-petrovic/js-dxf#87]
i am trying to find the end of an arc so that I can draw the following shape:

![image](https://user-images.githubusercontent.com/895340/187067435-a97b8ba8-900e-41e9-9a6e-66d2eac66e1c.png)

it is an arc with an inside arc obviously then closed with two end lines.
is it possible?
fyi: the resulting arcs should fit inside a parent circle...

**Comment by tarikjabiri** [comment]
Hi,

What do you mean by end of the arc is it the coordinates of the start and the end of the arc.

**Comment by ashleycoker** [comment]
Yes, when you draw an arc (or a line,shape etc), for it to return the
coordinates of the end position, so that you can start your next shape from
there.

*Ashley Coker,* CEO
*w*: AskSlate.com
*e*: ***@***.***
*m*: +44 77382 64519
Unit 7, Fosters Business Park, Old School Road, Hook, Hampshire (Company
No. 06898498)

**Comment by tarikjabiri** [comment]
Ok

Note that `dxf-writer` can't do that for you. So you have to keep track of things like that for yourself.
The coordinates of the start and end of the arc are simple to get.
Ex:
Consider an arc defined like this:
- `cx` : x coordinate of the center.
- `cy` : y coordinate of the center.
- `r`: the radius.
- `sa`: start angle
- `ea`: endAngle

```js
// Coordinate of the start
const xstart = cx + r * Math.cos(sa);
const ystart = cy + r * Math.sin(sa);
// Coordinate of the end
const xend = cx + r * Math.cos(ea);
const yend = cy + r * Math.sin(ea);
```

**Comment by ashleycoker** [comment]
It seems that this works for the start point but not the end point?
If I draw a line between the two end points it seems further around the
circle that I would expect.
The start line works.
Any pointers?

[image: Capture.PNG]

*Ashley Coker,* CEO
*w*: AskSlate.com
*e*: ***@***.***
*m*: +44 77382 64519
Unit 7, Fosters Business Park, Old School Road, Hook, Hampshire (Company
No. 06898498)
