### ISSUE TITLE
how to dimensions？ 

### ISSUE THREAD

**Issue by ghost** [ognjen-petrovic/js-dxf#95]
how to dimensions？

**Comment by tarikjabiri** [comment]
Unfortunately dimensions aren't supported

**Comment by ghost** [comment]
so pity, thinks bro.

**Comment by tarikjabiri** [comment]
You can use [@tarikjabiri/dxf](https://github.com/dxfjs/writer). It supports dimensions.

**Comment by ognjen-petrovic** [comment]
Thanks @tarikjabiri
