### ISSUE TITLE
Spline control point order?

### ISSUE THREAD

**Issue by forresto** [ognjen-petrovic/js-dxf#97]
Documentation request, what is the order of control points? For my library's bezier path conversion to DXF, I have this working. Are these assumptions correct around 

* anchor positions and handles
* path `closed`

?

<details>
<summary>my incorrect code</summary> 

```ts
// @ts-ignore line -- drawSpline is missing from types
d.drawSpline(pathToDXFSplinePoints(path), 3);

/**
 * Given a Cuttle `Path`, return the array of points to make a DXF spline.
 */
function pathToDXFSplinePoints(path: CuttlePath): Array<[number, number]> {
  const { anchors, closed } = path;

  const splinePoints: Array<[number, number]> = [];

  for (let i = 0, len = anchors.length; i < len; i++) {
    const { position, handleIn, handleOut } = anchors[i];

    const handleInA = position.clone().add(handleIn);
    const handleOutA = position.clone().add(handleOut);

    if (i > 0) {
      // y is flipped in DXF vs Cuttle
      splinePoints.push([handleInA.x, 0 - handleInA.y]);
    }
    splinePoints.push([position.x, 0 - position.y]);
    splinePoints.push([handleOutA.x, 0 - handleOutA.y]);
  }

  if (closed) {
    const { position, handleIn } = anchors[0];
    const handleInA = position.clone().add(handleIn);
    splinePoints.push([handleInA.x, 0 - handleInA.y]);
    splinePoints.push([position.x, 0 - position.y]);
  }

  return splinePoints;
}
```

**Comment by tarikjabiri** [comment]
Hi

Not sure about your problem, but the DXF uses [NURBS](https://www.rhino3d.com/features/nurbs/).

And for the closed spline you need to set flag = 1, not sure about the implementation here you can see:
<img width="418" alt="github" src="https://user-images.githubusercontent.com/6343314/227949712-bc7c3917-de8a-499e-bf57-b54cd1d9c2b4.png">

its 0 by default here you can see

**Comment by forresto** [comment]
I misunderstood how to translate our bezier path to splines. I needed to convert our path into segments, and make one spline per segment, with these points: `[startPoint, startPointHandleOut, endPointHandleIn, endPoint]`

**Comment by tarikjabiri** [comment]
How is your bezier path defined?

You need controle points or fit points.

**Comment by forresto** [comment]
Here is the correct translation from our library:

```
const segments = path.segments();
for (let segment of segments) {
  const {startPoint, startPointHandleOut, endPointHandleIn, endPoint} = segment;
  const points = [startPoint, startPointHandleOut, endPointHandleIn, endPoint];
  d.drawSpline(points, 3);
}
```

Thanks for looking.

**Comment by tarikjabiri** [comment]
Ok so those points are the control points, but is your path composed of small bezier curves or its only one entity and you split it using the `segments()` method?

- If its one entity, also the dxf spline can represent a big spline with many control points (try to group those points in one array and use it like that and see the result, to create one dxf entity).
- If its like that by default so this is the best way.

Regards.

**Comment by forresto** [comment]
Yes, our paths are an array of anchors, each with position, handle in, and handle out. Our `path.segments()` returns an array of cubic bezier segments, which translate like that to multiple `drawSpline(points, 3)` calls.
